[versions]
agp = "8.6.1"
android = "8.7.3"
kotlin = "2.0.20"
constraintLayout = "2.2.1"
coordinatorLayout = "1.3.0"
cardview = "1.0.0"
appcompat = "1.7.1"
transition = "1.6.0"
photoview = "2.3.0"
glide = "4.16.0"
media3 = "1.7.1"
material = "1.12.0"

[libraries]
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
cardview = { module = "androidx.cardview:cardview", version.ref = "cardview" }
material = { module = "com.google.android.material:material", version.ref = "material" }
coordinatorLayout = { module = "androidx.coordinatorlayout:coordinatorlayout", version.ref = "coordinatorLayout" }
constraintLayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintLayout" }
transition = { module = "androidx.transition:transition", version.ref = "transition" }
photoview = { module = "com.github.chrisbanes:PhotoView", version.ref = "photoview" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
media3 = { module = "androidx.media3:media3-exoplayer", version.ref = "media3" }
media3ui = { module = "androidx.media3:media3-ui", version.ref = "media3" }
media3dash = { module = "androidx.media3:media3-exoplayer-dash", version.ref = "media3" }
media3hls = { module = "androidx.media3:media3-exoplayer-hls", version.ref = "media3" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
android-application = { id = "com.android.application", version.ref = "android" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }